# [[main]]
    # Top-level menu entry
#   identifier = "work"
#    name = "Work"
#    url = "/projects/"
#    weight = 1

# [[main]]
#    identifier = "projects"
#    name = "Projects"
#    url = "/projects/"
#    parent = "work"
#    weight = 1

[[main]]
    identifier = "journey"
    name = "Journey"
    url = "/journey/"
    weight = 1

# [[main]]
#    identifier = "contact"
#    name = "Contact"
#    url = "/contact/"
#    parent = "work"
#    weight = 3

# [[main]]
    # Top-level menu entry
#    identifier = "writing"
#    name = "Writing"
#    url = "/posts/"
#    weight = 4

[[main]]
# Top-level menu entry
    identifier = "posts"
    name = "Bytes Bay Blog"
    url = "/posts/"
    weight = 1

# [[main]]
#    identifier = "subsection"
#    name = "Subsection"
#    url = "/subsection/"
#    url = "/posts/subsection/" # Remove url param from subsection/_index.md frontmatter to use full permalink
#    parent = "posts"
#    weight = 2

# [[main]]
    # Top-level menu entry
#    identifier = "explore"
#    name = "Explore"
#    url = "/categories/"
#    weight = 6

# [[main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories/"
#    parent = "explore"
#    weight = 6

# [[main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags/"
#    parent = "explore"
#    weight = 7

# [[main]]
#    identifier = "series"
#    name = "Series"
#    url = "/series/"
#    parent = "explore"
#    weight = 8

# [[main]]
#    identifier = "project-type"
#    name = "Project Types"
#    url = "/project-types/"
#    parent = "explore"
#    weight = 9